tact-lang/web-ide

package-lock.json
package.json

chore: Update @tact-lang/compiler to version 1.3.1

---

package-lock.json
package.json
src/components/workspace/ABIUi/ABIUi.tsx
src/components/workspace/BuildProject/BuildProject.tsx
src/hooks/contract.hooks.ts
src/interfaces/workspace.interface.ts
src/utility/utils.ts

fix: resolve post-reload interaction issues with deployed contracts

---

src/components/workspace/WorkSpace/WorkSpace.tsx

feat/fix: auto open template contract in editor

---

package-lock.json
package.json
src/assets/ton/tact/tmLanguage.json

chore: update @tact-lang/compiler to version 1.4

---

src/components/shared/LogView/LogView.tsx
src/components/workspace/TestCases/TestCases.tsx
src/pages/_app.tsx
src/utility/eventEmitter.ts
types/global.d.ts

fix(logging): resolve redundant log entry for test cases

---

src/utility/abi.ts

feat(ABI): build generic data collection from ABI

---

src/utility/abi.ts

Generate initialization parameters from compiler context

---

package-lock.json
package.json
src/assets/ton/tact/tmLanguage.json
src/hooks/project.hooks.ts

chore: update @tact-lang/compiler to version 1.4.1

---

package-lock.json
package.json
src/hooks/project.hooks.ts
src/utility/abi.ts
src/utility/tactLogger.ts

chore: upgrade to @tact-lang/compiler v1.4.2

---

package-lock.json
package.json

chore: upgrade `@tact-lang/compiler` to v1.4.3

---

package-lock.json
package.json
src/components/workspace/Editor/Editor.module.scss
src/components/workspace/Editor/Editor.tsx
src/components/workspace/WorkspaceSidebar/WorkspaceSidebar.tsx
src/hooks/setting.hooks.ts
src/interfaces/setting.interface.ts
src/state/setting.state.ts
types/monaco-vim.d.ts

feat: add Vim mode integration

---

src/components/workspace/Editor/Editor.tsx

fix: setup editor mode post editor mount

---

package-lock.json
package.json

chore: upgrade `@tact-lang/compiler` to v1.4.4

---

src/components/shared/LogView/LogView.module.scss
src/components/shared/LogView/LogView.tsx
src/components/workspace/ABIUi/TactABIUi.tsx
src/hooks/contract.hooks.ts
src/utility/utils.ts

feat: pretty print getter result

---

src/hooks/logActivity.hooks.ts
src/utility/utils.ts

fix: remove html log message parsing

---

src/components/workspace/BuildProject/BuildProject.tsx
src/utility/utils.ts

fix: convert HTML logs to ANSI format

---

package-lock.json
package.json
src/assets/ton/tact/tmLanguage.json
src/hooks/project.hooks.ts

chore: upgrade `@tact-lang/compiler` to v1.5

---

src/components/workspace/BuildProject/BuildProject.tsx

feat: auto select first contract for deploy

---

src/components/project/DownloadProject/DownloadProject.module.scss
src/components/project/DownloadProject/DownloadProject.tsx
src/components/project/DownloadProject/index.ts
src/components/project/index.ts
src/components/workspace/WorkSpace/WorkSpace.module.scss
src/components/workspace/WorkSpace/WorkSpace.tsx
src/components/workspace/project/ManageProject/ManageProject.tsx
src/components/workspace/tree/FileTree/FileTree.module.scss

feat: add download feature for all or individual projects

---

src/components/project/MigrateToUnifiedFS/MigrateToUnifiedFS.tsx
src/utility/eventEmitter.ts

fix: resolve migration status sync issue

---

src/components/project/CloneProject/CloneProject.module.scss
src/components/project/CloneProject/CloneProject.tsx
src/components/project/CloneProject/index.ts
src/components/project/MigrateToUnifiedFS/MigrateToUnifiedFS.tsx
src/components/project/NewProject/NewProject.tsx
src/components/project/index.ts
src/components/ui/icon/index.tsx
src/components/workspace/BuildProject/BuildProject.tsx
src/components/workspace/ContractInteraction/FuncContractInteraction.tsx
src/components/workspace/ContractInteraction/TactContractInteraction.tsx
src/components/workspace/Tabs/Tabs.tsx
src/components/workspace/project/ManageProject/ManageProject.tsx
src/components/workspace/tree/FileTree/ItemActions.tsx
src/components/workspace/tree/FileTree/TreeNode.tsx
src/enum/file.ts
src/hooks/projectV2.hooks.ts
src/interfaces/workspace.interface.ts
src/lib/fs.ts
src/styles/global.scss

feat: add contract file sharing with Base64-encoded URL

---

src/lib/polyfills.ts
src/pages/_app.tsx

fix: add polyfills for Set.prototype.isSubsetOf

---

src/components/workspace/TestCases/TestCases.tsx

fix: absolute path for FunC test cases

---

src/components/project/NewProject/NewProject.tsx
src/components/workspace/project/ManageProject/ManageProject.tsx
src/lib/fs.ts
src/lib/zip.ts
src/utility/gitRepoDownloader.ts

feat(import): improve GitHub repository import process

---

src/components/workspace/Editor/Editor.tsx
src/components/workspace/Tabs/Tabs.tsx
src/components/workspace/tree/FileTree/TreeNode.tsx
src/hooks/fileTabs.hooks.ts
src/hooks/projectV2.hooks.ts
src/utility/eventEmitter.ts

fix: syntax highlighting and tab inconsistency on rename

---

src/utility/utils.ts

fix: correct Base64 decoding to support UTF-8 characters

---

commitlint.config.ts
src/components/project/NewProject/NewProject.module.scss
src/components/shared/LogView/LogView.module.scss
src/components/shared/LogView/LogView.tsx
src/components/shared/ThemeProvider/ThemeProvider.tsx
src/components/shared/ThemeProvider/index.ts
src/components/shared/index.ts
src/components/template/ProjectTemplate/ProjectTemplate.tsx
src/components/ui/icon/index.tsx
src/components/workspace/ABIUi/ABIUi.module.scss
src/components/workspace/BottomPanel/BottomPanel.module.scss
src/components/workspace/BuildProject/BuildProject.module.scss
src/components/workspace/Editor/Editor.module.scss
src/components/workspace/Editor/Editor.tsx
src/components/workspace/Tabs/Tabs.module.scss
src/components/workspace/WorkSpace/WorkSpace.module.scss
src/components/workspace/WorkspaceSidebar/WorkspaceSidebar.module.scss
src/components/workspace/WorkspaceSidebar/WorkspaceSidebar.tsx
src/components/workspace/project/ManageProject/ManageProject.module.scss
src/interfaces/setting.interface.ts
src/pages/_app.tsx
src/state/IDE.context.tsx
src/styles/components/file-icons.scss
src/styles/components/project.scss
src/styles/global.scss
src/styles/lib/form.scss

feat(theme): add support for light theme

---

.eslintrc.cjs
.github/workflows/deploy.yml
.prettierignore
Dockerfile
helm/app/templates/deployment.yaml
helm/app/values.yaml
package-lock.json
package.json

update env docker build

---

src/lib/fs.ts

fix: "indexedDB is not defined" with @isomorphic-git/lightning-fs (SSR)

---

package-lock.json
package.json
src/hooks/fileTabs.hooks.ts
src/schemas/fileTab.schema.ts

fix(file-tab): handle prior `active` file path format

---

package-lock.json
package.json
src/components/workspace/WorkspaceSidebar/WorkspaceSidebar.tsx
src/hooks/project.hooks.ts
src/hooks/setting.hooks.ts
src/interfaces/setting.interface.ts
src/pages/_app.tsx

feat: add masterchain support and bump `@ton/sandbox`

---

package-lock.json
package.json
src/components/shared/LogView/LogView.tsx
src/components/shared/LogView/hooks/useLogFilter.ts
src/components/shared/LogView/hooks/useTerminal.ts
src/components/shared/LogView/utils/constants.ts
src/components/shared/LogView/utils/formatTimestamp.ts
src/components/workspace/TestCases/TestCases.tsx
src/utility/eventEmitter.ts
src/utility/terminal/xtermWebLinkProvider.ts

Implemented functionality to detect hover events on terminal exit codes.
Refactored log viewer code base.
Resolves #215

feat: add terminal hover detection for exit codes

---

src/components/shared/LogView/LogPopover.tsx
src/components/shared/LogView/LogView.module.scss
src/components/shared/LogView/LogView.tsx
src/components/shared/LogView/hooks/useTerminal.ts
src/constant/ansiCodes.ts
src/constant/exitCodes.ts
src/hooks/contract.hooks.ts

feat: display popover on Exit code hover

---

package-lock.json
package.json
src/components/shared/LogView/LogPopover.tsx
src/components/shared/LogView/LogView.module.scss
src/components/shared/LogView/LogView.tsx
src/components/shared/LogView/hooks/useLogFilter.ts
src/components/shared/LogView/hooks/useTerminal.ts
src/components/shared/LogView/utils/constants.ts
src/components/shared/LogView/utils/formatTimestamp.ts
src/components/workspace/TestCases/TestCases.tsx
src/constant/ansiCodes.ts
src/constant/exitCodes.ts
src/hooks/contract.hooks.ts
src/utility/eventEmitter.ts
src/utility/terminal/xtermWebLinkProvider.ts

feat: display exit code details

---

src/components/MistiStaticAnalyzer/MistiStaticAnalyzer.tsx
src/components/shared/LogView/LogView.tsx
src/components/shared/LogView/hooks/useTerminal.ts
src/components/shared/LogView/utils/constants.ts
src/constant/ansiCodes.ts
src/utility/utils.ts

Resolves #296 
Resolves #286 
Resolves #280

feat(misti): improve log clarity and display misti version

---

src/components/MistiStaticAnalyzer/MistiStaticAnalyzer.tsx

fix(misti): exclude unsupported detectors

---

src/components/shared/LogView/LogView.tsx

fix: auto-scroll in log pane

---

src/components/workspace/tree/FileTree/TreeNode.tsx

fix: resolve inability to create subfolders and files

---

package-lock.json
package.json
src/assets/ton/tact/tmLanguage.json
src/components/MistiStaticAnalyzer/MistiStaticAnalyzer.tsx
src/components/workspace/WorkspaceSidebar/WorkspaceSidebar.tsx
src/hooks/project.hooks.ts
src/hooks/setting.hooks.ts
src/interfaces/setting.interface.ts
src/utility/abi.ts

feat: add support for Tact 1.6

---

src/components/workspace/WorkSpace/WorkSpace.tsx
src/components/workspace/tree/FileTree/FileTree.module.scss
src/components/workspace/tree/FileTree/FileTree.tsx
src/components/workspace/tree/FileTree/TreeNode.tsx
src/utility/eventEmitter.ts

Resolves #232
Resolves #248 
Resolves #287

feat: improve root file/folder creation UX & auto-open new file

---

src/components/git/ManageGit/ManageGit.tsx
src/components/ui/AppLogo/AppLogo.module.scss
src/components/ui/AppLogo/AppLogo.tsx
src/components/workspace/BuildProject/BuildProject.module.scss
src/components/workspace/BuildProject/BuildProject.tsx
src/components/workspace/WorkSpace/WorkSpace.module.scss
src/components/workspace/WorkSpace/WorkSpace.tsx
src/components/workspace/WorkspaceSidebar/WorkspaceSidebar.tsx
src/components/workspace/project/ManageProject/ManageProject.module.scss
src/components/workspace/tree/FileTree/TreeNode.tsx
src/styles/global.scss

chore: move Web IDE logo

---

src/components/project/NewProject/NewProject.tsx

chore: set blank contract template as default for new projects

---

package-lock.json
package.json
src/hooks/project.hooks.ts

chore: bump tact to 1.6.3

---

src/components/MistiStaticAnalyzer/MistiStaticAnalyzer.tsx

fix: automatically set default severity level in Misti

---

src/components/MistiStaticAnalyzer/MistiStaticAnalyzer.tsx

chore: remove Misti level reset option

---

src/components/workspace/ABIUi/ABIUi.module.scss
src/components/workspace/BuildProject/BuildProject.tsx
src/components/workspace/ExecuteFile/ExecuteFile.tsx
src/components/workspace/TestCases/TestCases.tsx
src/hooks/project.hooks.ts
src/hooks/projectV2.hooks.ts
src/interfaces/workspace.interface.ts
src/utility/file.ts

fix: ensure contract build and deployment remain in sync

---

src/lib/zip.ts

fix: ensure empty directory is included in exported project

---

src/App.tsx

fix: upgrade `@ton/core` to resolve test case failures

---

package-lock.json
package.json

chore: bump Tact to 1.6.4

---

src/components/MistiStaticAnalyzer/MistiStaticAnalyzer.tsx

fix: cannot run misti analyzer on new file

---

src/components/MistiStaticAnalyzer/MistiStaticAnalyzer.tsx

feat(misti): auto-select opened contract file

---

src/assets/vscode-light.ts
src/components/workspace/Editor/Editor.tsx
src/utility/syntaxHighlighter.ts

fix: unify comment styling in light theme

---

src/components/workspace/ABIUi/ABIUi.module.scss
src/components/workspace/BuildProject/BuildProject.tsx
src/hooks/contract.hooks.ts

feat: support deployment via empty receiver and refactor contract deployment

---

src/components/workspace/project/ManageProject/ManageProject.module.scss
src/components/workspace/project/ManageProject/ManageProject.tsx

feat: support import even if no projects are created

---

package-lock.json
package.json

Closes https://github.com/tact-lang/web-ide/issues/353

chore: update @tact-lang/compiler to 1.6.5

---

src/components/workspace/Tabs/Tabs.tsx
src/components/workspace/tree/FileTree/FileTree.module.scss
src/components/workspace/tree/FileTree/FileTree.tsx
src/components/workspace/tree/FileTree/TreeNode.tsx
src/hooks/projectV2.hooks.ts

feat: improve file drag UI/UX, fix bug when moving file to root

---

src/components/workspace/ABIUi/TactABIUi.tsx

fix: allow sending empty messages

---

src/hooks/contract.hooks.ts

fix: getter method call for on-chain contract

---

package-lock.json
package.json
src/components/MistiStaticAnalyzer/MistiStaticAnalyzer.tsx
src/utility/utils.ts
webpack/webpack.prod.mjs

Closes #324
Closes #325
Closes #372

chore: bump misti to 0.8.0

---

src/components/workspace/ABIUi/TactABIUi.tsx
src/components/workspace/ABIUi/TonSendMode.tsx
src/components/workspace/ABIUi/TonValueInput.tsx
src/components/workspace/BuildProject/BuildProject.tsx
src/components/workspace/ContractInteraction/FuncContractInteraction.tsx
src/components/workspace/WorkspaceSidebar/AppSetting.tsx
src/hooks/contract.hooks.ts
src/hooks/setting.hooks.ts
src/interfaces/setting.interface.ts
src/state/IDE.context.tsx

feat: allow specifying TON value and send mode per message

---

src/components/workspace/BuildProject/BuildProject.module.scss
src/components/workspace/BuildProject/BuildProject.tsx
src/components/workspace/WorkSpace/WorkSpace.tsx
src/components/workspace/globalWorkspace.ts
src/hooks/contract.hooks.ts
src/utility/utils.ts

feat: support multiple wallets in sandbox mode

---

src/components/shared/CodeBlock/CodeBlock.module.scss
src/components/shared/CodeBlock/CodeBlock.tsx
src/components/shared/CodeBlock/index.ts
src/components/ui/icon/index.tsx
src/components/workspace/ABIUi/TactABIUi.tsx
src/components/workspace/ExecuteFile/ExecuteFile.tsx

Resolves #299 
Resolves #376 
Resolves #380

feat: improve cell help UI/UX flow

---

package-lock.json
package.json
src/components/MistiStaticAnalyzer/MistiStaticAnalyzer.tsx
src/hooks/project.hooks.ts
webpack/webpack.common.mjs

chore: update @tact-lang/compiler to 1.6.6

---

src/components/workspace/ABIUi/ABIUi.module.scss
src/components/workspace/ABIUi/TonValueInput.tsx
src/components/workspace/ContractVerifier/ContractVerifier.module.scss
src/components/workspace/ContractVerifier/ContractVerifier.tsx

fix: improve UI for TON input value and verifier address field

---

src/components/shared/LogView/hooks/useTerminal.ts
src/components/shared/LogView/utils/constants.ts

feat: implement terminal themes for light and dark modes

---

package-lock.json
package.json
src/assets/ton/tact/tmLanguage.json

chore: update @tact-lang/compiler to 1.6.7
